#!/usr/bin/env ruby

files = Dir.glob('*.js')
files.delete('all.js')

scripts = []
files.each do |file|
  host = file.gsub(/\.js$/, '')
  js   = File.read(file)

  scripts << "(location.href.match(/^https?:\\\/\\\/#{host}/)) {\n#{js}}"
end

all_js = "if #{scripts.join(' else if ')}"
File.write('all.js', all_js)
