#!/usr/bin/env bash

user=k0kubun
repo=dotfiles
branch=master

tempdir=/tmp
archive=${tempdir}/${repo}.zip
unzipped=${tempdir}/${repo}-${branch}

userdir=${HOME}/src/github.com/${user}
repodir=${userdir}/${repo}

# Fetch repository to /tmp/dotfiles-master
curl -L -o $archive https://github.com/${user}/${repo}/archive/${branch}.zip
unzip -o $archive -d $tempdir

# Move /tmp/dotfiles-master to ~/src/github.com/k0kubun/dotfiles
mkdir -p $userdir
rm -rf $repodir
mv $unzipped $repodir

# Run installer
pushd $repodir
./install

# Cleanup
popd
rm $archive
