#!/usr/bin/env ruby

files = Dir.glob('*.js')
files.delete('all.js')

scripts = []
files.each do |file|
  host = file.gsub(/\.js$/, '')
  js   = File.read(file).gsub(/^/, '  ')

  scripts << "(location.href.match(/^https?:\\\/\\\/(www\.|)#{host}/)) {\n#{js}}"
end

all_js = "if #{scripts.join(' else if ').gsub(/\A  /, '')}".gsub(/^ +$/, '')
File.write('all.js', all_js)
