#!/bin/sh

keyword=$1
shift

match=$(wmctrl -l | grep "$(hostname) ${keyword}")
case $? in
  1)
    $@
    ;;
  0)
    window_id=$(echo $match | tail -n1 | cut -d' ' -f1)
    wmctrl -i -R $window_id
    ;;
esac
