#!/usr/bin/env ruby

require 'date'

def stats(desc, from, to = from)
  command = "git log" <<
    " --oneline" <<
    " --shortstat" <<
    " --no-merges" <<
    " --since='#{from.strftime('%Y-%m-%d')} 00:00:00'" <<
    " --until='#{to.strftime('%Y-%m-%d')} 23:59:00'"
  output = `#{command}`
  lines = output.split(/\n/).grep(/files? changed/)
  insertions = 0
  deletions = 0
  lines.each do |line|
    words = line.split(' ')
    insertions += words[3].to_i
    deletions  += words[5].to_i
  end
  puts desc
  puts "  #{insertions} insertions(+), #{deletions} deletions(-)"
end

stats 'This week',  Date.today - 6, Date.today
stats 'Today',      Date.today
stats 'Yesterday',  Date.today - 1
stats '2 days ago', Date.today - 2
stats '3 days ago', Date.today - 3
stats '4 days ago', Date.today - 4
stats '5 days ago', Date.today - 5
stats '6 days ago', Date.today - 6
